services:
  querygenie-client:
    build:
      context: D:/Coding/web/Projects/querygenie/client
    image: aashishpal09/querygenie-client:1.0.0
    container_name: querygenie-client
    env_file:
      - D:/Coding/web/Projects/querygenie/client/.env.prod
    ports:
      - 3000:3000
    restart: always
    depends_on:
      querygenie-server:
        condition: service_healthy
    volumes:
      - log-data:/app/logs

  querygenie-server:
    build:
      context: D:/Coding/web/Projects/querygenie/server
    image: aashishpal09/querygenie-server:1.0.1
    container_name: querygenie-server
    env_file:
      - D:/Coding/web/Projects/querygenie/server/.env.prod
    ports:
      - 5000:5000
    restart: on-failure
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5000" ]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      qdrant:
        condition: service_healthy
    volumes:
      - log-data:/app/logs

volumes:
  log-data:
    driver: local
    driver_opts:
      type: none
      device: D:/Coding/web/Projects/querygenie/data/logs
      o: bind
